_target_: core.datasets.zju.NoisyZJUH36MDataset
h5_path: data/h36m_zju/${.subject}_train.h5


cache_dir: outputs/zju_noise/
perturb_proportion: 0.5
perturb_strength: 0.6
split: train
patch_size: 1
subject: S7
mask_img: True
perturb_bg: True


ray_sampler:
  _target_: core.utils.mcmc.MetropolisRaySampler
